config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'

  resources :posts do
    resources :comments
  end

  get '/sign_in', to: 'users#sign_in'
  post '/sign_in', to: 'users#sign_in!'
  get '/sign_up', to: 'users#sign_up'
  post '/sign_up', to: 'users#sign_up!'
  get '/sign_out', to: 'users#sign_out'
end

app/models/ability.rb
class Ability
  # were you able to incorpoate cancan? I think its implementation isn't too complicated.
  include CanCan::Ability

  def initialize(user)
    can :manage, Post, :user_id => @current_user
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post
    belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # nice you have some validations! legit. associations and other models look good.
  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true
  has_secure_password
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate

  def current_user
    @current_user = User.find(session[:user]["id"])
  end

  private
  def authenticate
    if !session[:user]
      redirect_to "/sign_in"
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

#@Current_User is in a lot of places - i was having issues getting the edit and delete buttons to only show for the current user

# you could always create a current_user helper method
def new
  @post = Post.find(params[:post_id])
  @comment = Comment.new
end

def edit
  @comment = Comment.find(params[:id])
  @post = Post.find(params[:post_id])
  @current_user = User.find(session[:user]["id"])
end

def update
  @comment = Comment.find(params[:id])
  @post = Post.find(params[:post_id])
  @comment.update(comment_params.merge(post: @post))
  redirect_to (post_path(@post))
end

def create
  @post = Post.find(params[:post_id])
  @user = User.find(session[:user]["id"])
  @comment = @user.comments.create!(comment_params.merge(post: @post))
  redirect_to (post_path(@post))

end

def show
  @current_user = User.find(session[:user]["id"])
  @comment = Comment.all
end

def destroy
  @comment = Comment.find(params[:id])
  @comment.destroy
  redirect_to posts_path
end

private
def comment_params
  params.require(:comment).permit(:author, :comment_body, :user)
end



end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

# I was curious as to why you didn't include edit/update functionality for the
# posts. Other than that posts controller looks great, little bit of indentation issues
  def index
     @posts = Post.all
  end

def show
  @current_user = User.find(session[:user]["id"])
  @post = Post.find(params[:id])

end

def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
end

def new
  @post = Post.new
end

def create
  @user = User.find(session[:user]["id"])
  @post = @user.posts.create!(post_params)
  redirect_to (post_path(@post))

end



private
def post_params
  params.require(:post).permit(:title, :post_body, :photo_url)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authenticate
# nice hand rolled user auth. sick
  def sign_up
  end

  def sign_up!
    user = User.new(
      username: params[:username],
      password_digest: BCrypt::Password.create(params[:password])
    )
    if params[:password_confirmation] != params[:password]
      message = "Your passwords don't match!"
    elsif user.save
      message = "Your account has been created!"
    else
      message = "Your account couldn't be created. Did you enter a unique username and password?"
    end
    flash[:notice] = message
    redirect_to action: :sign_in
  end

  def sign_in
  end

  def sign_in!
    @user = User.find_by(username: params[:username])
    if !@user
      message = "This user doesn't exist!"
    elsif !BCrypt::Password.new(@user.password_digest).is_password?(params[:password])
      message = "Your password's wrong!"
    else
      message = "You're signed in, #{@user.username}! "
      cookies[:username] = {
      value: @user.username,
      expires: 100.years.from_now
      }
      session[:user] = @user
    end
    flash[:notice] = message
    redirect_to posts_path
  end

  def sign_out
    reset_session
    flash[:notice] = "You're signed out!"
    redirect_to root_url
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/edit.html.erb
<%=form_for([@post, @comment]) do |f| %>

<div class="commentTextBox">
  <%= f.text_field :comment_body, placeholder: "Comment", size: "100" %>

<p>
<%= f.submit %>
</p>
<% end %>
</div>

app/views/comments/new.html.erb
<%=form_for([@post, @comment]) do |f| %>

<div class="commentTextBox">
  <%= f.text_field :comment_body, placeholder: "Comment", size: "100" %>

<p>
<%= f.submit %>
</p>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KetoCookBook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav id="topNav">
    <ul>
    <% if session[:user] %>
      <li><a href="/sign_out"><%= session[:user]["username"] %>: sign out</a></li>
      <li><a href="/">Home</a></li>
    <% else %>
      <li><a href="/sign_up">Sign up</a></li>
      <li><a href="/sign_in">Sign in</a></li>
    <% end %>
    <li><%= link_to "Add New Recipe", new_post_path(@post) %></li>
    <li><a href="http://www.reddit.com/r/keto">What is Keto?</a></li>
    <li><a href="http://www.reddit.com/r/ketogains">Do you lift, bro?</a></li>
    <li><a href="http://M00staff.github.io">Back to GitHub Pages</a></li>
  </ul>
  </nav>

<div class="sideBar">
  <ul>
    <li></li>
    <li>The KetoCookBook is an online database for submitting and storing your low-carb recipies and ideas</li>
    <li></li>
    <li>Please feel free to submit whatever you want</li>
    <li></li>
    <li>For more information about a Ketogenic diet visit <a href "www.reddit.com/r/keto">reddit.com/r/keto</a></li>
  </ul>
</div>

  <h1>The Keto Cook Book</h1>



<%= flash[:notice] %>

<!--  wrapping the yeild in a Div really helped with the overall formatting, useful trick for CSS, i can thank Nick for that -->

<div class="mainBody">
<%= yield %>
</div>

</body>
</html>

app/views/posts/index.html.erb
<div class="homeIndex">
  <ul>
    <% @posts.each do |post| %>
    <li>
      <%= link_to "#{post.user.try(:username)} - #{post.title}", post_path(post) %>
    </li>
    <% end %>
  </ul>
</div>

app/views/posts/new.html.erb
<div class="newPost">

  <%=form_for @post do |f| %>

  <div id="photoTextBox">
    <%= f.text_field :title, size: "50x5", :placeholder => "title" %>
    <%= f.text_field :photo_url, size: "50x5", :placeholder => "Photo_url" %>
  </div>

  <div id="postTextBox">
    <%= f.text_area :post_body, size: "101.5x10", :placeholder => "Recipe" %>
  </div>

  <%= f.submit %>
  <% end %>
</div>

app/views/posts/show.html.erb
<p class="showPostHeading">User <%= @post.user.try(:username) %>'s <%= @post.title %> </p>

<div class="photoShow">
  <%= image_tag("#{@post.photo_url}", :class => "imageShow") %>
</div>

<p class="postBodyShowPost"> <%= simple_format(@post.post_body, class: 'postBodyShowPost') %> </p>



<div class="commentSection">
  <p> comments </p>
<!-- I'm curious how the comments are indenting like that. Additionally, it would be
really nice if i could create a comment right on the show page. How could we incorporate that? -->
    <% @post.comments.each do |comment| %>
    <ul>
      <li><%= comment.user.try(:username) %> says</li>
      <%# if statement for showing edit button #%>
      <%= comment.comment_body %> <% if comment.user == @current_user %> <%= link_to "(Edit)", edit_post_comment_path(@post.id, comment.id) %> <% end %>
    <% end %>
    </ul>

<p id="addComment">
  <%= link_to "Add Comment", new_post_comment_path(@post.id) %>
</p>
</div>


<%# if statement for showing delete button #%>

<%= form_for(@post, method: :delete) do |f| %>
  <% if @post.user == @current_user %>
  <%= f.submit "Delete Post", class: "delete" %>
  <% end %>
<% end %>

app/views/users/sign_in.html.erb
<div class="signIn"
<h2>Sign in</h2>
<%= form_tag("/sign_in", method: "post") do %>
  <input type="text" name="username" placeholder="username" value="<%= cookies[:username] %>"/>
  <input type="password" name="password" placeholder="password" />
  <input type="submit" value="Sign in" />
<% end %>
</div>

app/views/users/sign_up.html.erb
<div class="signUp">
<h2>Sign Up</h2>
<%= form_tag("/sign_up", method: "post") do %>
  <input type="text" name="username" placeholder="username" />
  <input type="password" name="password" placeholder="password" />
  <input type="password" name="password_confirmation" placeholder="password again" />
  <input type="submit" value="Sign up" />
<% end %>
</div>